/*******************************************************************************
* Copyright (C) 2019-2023 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// RTDemo_MAX_alpha
// This file was @generated by ai8xize.py --test-dir synthed_net --prefix RTDemo_MAX_alpha --checkpoint-file trained/tinyfallnet-qat8-q.pth.tar --config-file networks/tinyfallnet.yaml --sample-input tests/sample_kfall.npy --device MAX78000 --board-name FTHR_RevA --compact-data --mexpress --timer 0 --display-checkpoint --verbose --overwrite

// DO NOT EDIT - regenerate this file instead!

// Configuring 24 layers
// Input data: HWC
// Layer 0: 6x50, no pooling, conv1d with kernel size 3, stride 1, pad 0, no activation, 64x48 output
// Layer 1: 64x48x1, max pool 2x1 with stride 2/2, no convolution, 64x24x1 output
// Layer 2: 64x24, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 64x24 output
// Layer 3: 64x24, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 16x24 output
// Layer 4: 16x24, no pooling, conv1d with kernel size 3, stride 1, pad 1, ReLU, 16x24 output
// Layer 5: 16x24, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 64x24 output
// Layer 6: 2x64x24x1, no pooling, 2-element add, no convolution, 64x24x1 output
// Layer 7: 64x24, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 64x24 output
// Layer 8: 64x24, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 16x24 output
// Layer 9: 16x24, no pooling, conv1d with kernel size 3, stride 1, pad 1, ReLU, 16x24 output
// Layer 10: 16x24, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 64x24 output
// Layer 11: 2x64x24x1, no pooling, 2-element add, no convolution, 64x24x1 output
// Layer 12: 64x24, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 64x24 output
// Layer 13: 64x24, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 16x24 output
// Layer 14: 16x24, no pooling, conv1d with kernel size 3, stride 1, pad 1, ReLU, 16x24 output
// Layer 15: 16x24, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 64x24 output
// Layer 16: 2x64x24x1, no pooling, 2-element add, no convolution, 64x24x1 output
// Layer 17: 64x24, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 64x24 output
// Layer 18: 64x24, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 16x24 output
// Layer 19: 16x24, no pooling, conv1d with kernel size 3, stride 1, pad 1, ReLU, 16x24 output
// Layer 20: 16x24, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 64x24 output
// Layer 21: 2x64x24x1, no pooling, 2-element add, no convolution, 64x24x1 output
// Layer 22: 64x24x1, max pool 2x1 with stride 2/2, no convolution, 64x12x1 output
// Layer 23: 64x12x1 flattened to 768x1x1, no pooling, linear, no activation, 2x1x1 output

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "gcfr_regs.h"
#include "cnn.h"
#include "weights.h"

void CNN_ISR(void)
{
  // Acknowledge interrupt to all quadrants
  *((volatile uint32_t *) 0x50100000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50500000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50900000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50d00000) &= ~((1<<12) | 1);

  CNN_COMPLETE; // Signal that processing is complete
#ifdef CNN_INFERENCE_TIMER
  cnn_time = MXC_TMR_SW_Stop(CNN_INFERENCE_TIMER);
#else
  cnn_time = 1;
#endif
}

int cnn_continue(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x50100000) |= 1; // Re-enable quadrant 0

  return CNN_OK;
}

int cnn_stop(void)
{
  *((volatile uint32_t *) 0x50100000) &= ~1; // Disable quadrant 0

  return CNN_OK;
}

void memcpy32(uint32_t *dst, const uint32_t *src, int n)
{
  while (n-- > 0) {
    *dst++ = *src++;
  }
}

static const uint32_t kernels[] = KERNELS;

int cnn_load_weights(void)
{
  uint32_t len;
  volatile uint32_t *addr;
  const uint32_t *ptr = kernels;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    *((volatile uint8_t *) ((uint32_t) addr | 1)) = 0x01; // Set address
    len = *ptr++;
    while (len-- > 0)
      *addr++ = *ptr++;
  }

  return CNN_OK;
}

static const uint8_t bias_0[] = BIAS_0;
static const uint8_t bias_1[] = BIAS_1;
static const uint8_t bias_2[] = BIAS_2;
static const uint8_t bias_3[] = BIAS_3;

static void memcpy_8to32(uint32_t *dst, const uint8_t *src, int n)
{
  while (n-- > 0) {
    *dst++ = *src++;
  }
}

int cnn_load_bias(void)
{
  memcpy_8to32((uint32_t *) 0x50108000, bias_0, sizeof(uint8_t) * 192);
  memcpy_8to32((uint32_t *) 0x50508000, bias_1, sizeof(uint8_t) * 176);
  memcpy_8to32((uint32_t *) 0x50908000, bias_2, sizeof(uint8_t) * 160);
  memcpy_8to32((uint32_t *) 0x50d08000, bias_3, sizeof(uint8_t) * 160);

  return CNN_OK;
}

int cnn_init(void)
{
  *((volatile uint32_t *) 0x50001000) = 0x00000000; // AON control
  *((volatile uint32_t *) 0x50100000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50100004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50100008) = 0x00000017; // Layer count
  *((volatile uint32_t *) 0x50500000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50500004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50500008) = 0x00000017; // Layer count
  *((volatile uint32_t *) 0x50900000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50900004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50900008) = 0x00000017; // Layer count
  *((volatile uint32_t *) 0x50d00000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50d00004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50d00008) = 0x00000017; // Layer count

  return CNN_OK;
}

int cnn_configure(void)
{
  // Layer 0 quadrant 0
  *((volatile uint32_t *) 0x50100010) = 0x00000031; // Rows
  *((volatile uint32_t *) 0x50100310) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50100410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100590) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50100a10) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50100610) = 0x000001f8; // Mask offset and count
  *((volatile uint32_t *) 0x50100110) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50100790) = 0x00025000; // Post processing register
  *((volatile uint32_t *) 0x50100710) = 0x003f003f; // Mask and processor enables

  // Layer 0 quadrant 1
  *((volatile uint32_t *) 0x50500010) = 0x00000031; // Rows
  *((volatile uint32_t *) 0x50500310) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50500410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500590) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50500a10) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50500610) = 0x000001f8; // Mask offset and count
  *((volatile uint32_t *) 0x50500110) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50500790) = 0x00024000; // Post processing register

  // Layer 0 quadrant 2
  *((volatile uint32_t *) 0x50900010) = 0x00000031; // Rows
  *((volatile uint32_t *) 0x50900310) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50900410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900590) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50900a10) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50900610) = 0x000001f8; // Mask offset and count
  *((volatile uint32_t *) 0x50900110) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50900790) = 0x00024000; // Post processing register

  // Layer 0 quadrant 3
  *((volatile uint32_t *) 0x50d00010) = 0x00000031; // Rows
  *((volatile uint32_t *) 0x50d00310) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00590) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d00a10) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00610) = 0x000001f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00110) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50d00790) = 0x00024000; // Post processing register

  // Layer 1 quadrant 0
  *((volatile uint32_t *) 0x50100014) = 0x0000002f; // Rows
  *((volatile uint32_t *) 0x50100194) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50100294) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100394) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50100594) = 0x000009a0; // Layer control
  *((volatile uint32_t *) 0x50100114) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x50100794) = 0x03000000; // Post processing register
  *((volatile uint32_t *) 0x50100714) = 0x0000ffff; // Mask and processor enables

  // Layer 1 quadrant 1
  *((volatile uint32_t *) 0x50500014) = 0x0000002f; // Rows
  *((volatile uint32_t *) 0x50500194) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50500294) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500314) = 0x00008000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500394) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50500594) = 0x000009a0; // Layer control
  *((volatile uint32_t *) 0x50500114) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x50500794) = 0x03000000; // Post processing register
  *((volatile uint32_t *) 0x50500714) = 0x0000ffff; // Mask and processor enables

  // Layer 1 quadrant 2
  *((volatile uint32_t *) 0x50900014) = 0x0000002f; // Rows
  *((volatile uint32_t *) 0x50900194) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50900294) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900314) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900394) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50900594) = 0x000009a0; // Layer control
  *((volatile uint32_t *) 0x50900114) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x50900794) = 0x03000000; // Post processing register
  *((volatile uint32_t *) 0x50900714) = 0x0000ffff; // Mask and processor enables

  // Layer 1 quadrant 3
  *((volatile uint32_t *) 0x50d00014) = 0x0000002f; // Rows
  *((volatile uint32_t *) 0x50d00194) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d00294) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00314) = 0x00018000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00394) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d00594) = 0x000009a0; // Layer control
  *((volatile uint32_t *) 0x50d00114) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x50d00794) = 0x03000000; // Post processing register
  *((volatile uint32_t *) 0x50d00714) = 0x0000ffff; // Mask and processor enables

  // Layer 2 quadrant 0
  *((volatile uint32_t *) 0x50100018) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50100318) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100598) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a18) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50100618) = 0x06c008b8; // Mask offset and count
  *((volatile uint32_t *) 0x50100118) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50100798) = 0x0002c000; // Post processing register
  *((volatile uint32_t *) 0x50100718) = 0xffffffff; // Mask and processor enables

  // Layer 2 quadrant 1
  *((volatile uint32_t *) 0x50500018) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50500318) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500598) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a18) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50500618) = 0x06c008b8; // Mask offset and count
  *((volatile uint32_t *) 0x50500118) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50500798) = 0x0002d000; // Post processing register
  *((volatile uint32_t *) 0x50500718) = 0xffffffff; // Mask and processor enables

  // Layer 2 quadrant 2
  *((volatile uint32_t *) 0x50900018) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50900318) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900598) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a18) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50900618) = 0x06c008b8; // Mask offset and count
  *((volatile uint32_t *) 0x50900118) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50900798) = 0x0002c000; // Post processing register
  *((volatile uint32_t *) 0x50900718) = 0xffffffff; // Mask and processor enables

  // Layer 2 quadrant 3
  *((volatile uint32_t *) 0x50d00018) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50d00318) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00418) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00598) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a18) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d00618) = 0x06c008b8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00118) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d00798) = 0x0002c000; // Post processing register
  *((volatile uint32_t *) 0x50d00718) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 0
  *((volatile uint32_t *) 0x5010001c) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x5010031c) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x5010041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5010059c) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a1c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5010061c) = 0x09000978; // Mask offset and count
  *((volatile uint32_t *) 0x5010011c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x5010071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 1
  *((volatile uint32_t *) 0x5050001c) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x5050031c) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x5050041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5050059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a1c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5050061c) = 0x09000978; // Mask offset and count
  *((volatile uint32_t *) 0x5050011c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x5050079c) = 0x00001080; // Post processing register
  *((volatile uint32_t *) 0x5050071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 2
  *((volatile uint32_t *) 0x5090001c) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x5090031c) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x5090041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5090059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a1c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5090061c) = 0x09000978; // Mask offset and count
  *((volatile uint32_t *) 0x5090011c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x5090071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 3
  *((volatile uint32_t *) 0x50d0001c) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50d0031c) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d0041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d0059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a1c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d0061c) = 0x09000978; // Mask offset and count
  *((volatile uint32_t *) 0x50d0011c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d0071c) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 0
  *((volatile uint32_t *) 0x50100020) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x50100420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100520) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x501005a0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50100a20) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100620) = 0x036003d8; // Mask offset and count
  *((volatile uint32_t *) 0x50100120) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50100720) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 1
  *((volatile uint32_t *) 0x50500020) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x50500420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500520) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x505005a0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a20) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500620) = 0x036003d8; // Mask offset and count
  *((volatile uint32_t *) 0x50500120) = 0x00001300; // 1D

  // Layer 4 quadrant 2
  *((volatile uint32_t *) 0x50900020) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x50900420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900520) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x509005a0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a20) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900620) = 0x036003d8; // Mask offset and count
  *((volatile uint32_t *) 0x50900120) = 0x00001300; // 1D

  // Layer 4 quadrant 3
  *((volatile uint32_t *) 0x50d00020) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x50d00420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00520) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005a0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a20) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00620) = 0x036003d8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00120) = 0x00001300; // 1D

  // Layer 5 quadrant 0
  *((volatile uint32_t *) 0x50100024) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50100324) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50100424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005a4) = 0x00004b20; // Layer control
  *((volatile uint32_t *) 0x50100a24) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50100624) = 0x0c600e58; // Mask offset and count
  *((volatile uint32_t *) 0x50100124) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x501007a4) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50100724) = 0xffffffff; // Mask and processor enables

  // Layer 5 quadrant 1
  *((volatile uint32_t *) 0x50500024) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50500324) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50500424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a24) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50500624) = 0x0c600e58; // Mask offset and count
  *((volatile uint32_t *) 0x50500124) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x505007a4) = 0x00022000; // Post processing register

  // Layer 5 quadrant 2
  *((volatile uint32_t *) 0x50900024) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50900324) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50900424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a24) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50900624) = 0x0c600e58; // Mask offset and count
  *((volatile uint32_t *) 0x50900124) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x509007a4) = 0x00023000; // Post processing register

  // Layer 5 quadrant 3
  *((volatile uint32_t *) 0x50d00024) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50d00324) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a24) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d00624) = 0x0c600e58; // Mask offset and count
  *((volatile uint32_t *) 0x50d00124) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d007a4) = 0x00022000; // Post processing register

  // Layer 6 quadrant 0
  *((volatile uint32_t *) 0x50100028) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x501003a8) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100528) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x501005a8) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50100128) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x501007a8) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50100728) = 0x0000ffff; // Mask and processor enables

  // Layer 6 quadrant 1
  *((volatile uint32_t *) 0x50500028) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50500328) = 0x00008000; // SRAM write ptr
  *((volatile uint32_t *) 0x505003a8) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500528) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x505005a8) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50500128) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x505007a8) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50500728) = 0x0000ffff; // Mask and processor enables

  // Layer 6 quadrant 2
  *((volatile uint32_t *) 0x50900028) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50900328) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003a8) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900528) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x509005a8) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50900128) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x509007a8) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50900728) = 0x0000ffff; // Mask and processor enables

  // Layer 6 quadrant 3
  *((volatile uint32_t *) 0x50d00028) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50d00328) = 0x00018000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003a8) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00528) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005a8) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d00128) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x50d007a8) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50d00728) = 0x0000ffff; // Mask and processor enables

  // Layer 7 quadrant 0
  *((volatile uint32_t *) 0x5010002c) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x5010032c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x5010042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005ac) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a2c) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x5010062c) = 0x0ea01098; // Mask offset and count
  *((volatile uint32_t *) 0x5010012c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x501007ac) = 0x00028000; // Post processing register
  *((volatile uint32_t *) 0x5010072c) = 0xffffffff; // Mask and processor enables

  // Layer 7 quadrant 1
  *((volatile uint32_t *) 0x5050002c) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x5050032c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x5050042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005ac) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a2c) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x5050062c) = 0x0ea01098; // Mask offset and count
  *((volatile uint32_t *) 0x5050012c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x505007ac) = 0x00028000; // Post processing register
  *((volatile uint32_t *) 0x5050072c) = 0xffffffff; // Mask and processor enables

  // Layer 7 quadrant 2
  *((volatile uint32_t *) 0x5090002c) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x5090032c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x5090042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005ac) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a2c) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x5090062c) = 0x0ea01098; // Mask offset and count
  *((volatile uint32_t *) 0x5090012c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x509007ac) = 0x00028000; // Post processing register
  *((volatile uint32_t *) 0x5090072c) = 0xffffffff; // Mask and processor enables

  // Layer 7 quadrant 3
  *((volatile uint32_t *) 0x50d0002c) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50d0032c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d0042c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005ac) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a2c) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d0062c) = 0x0ea01098; // Mask offset and count
  *((volatile uint32_t *) 0x50d0012c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d007ac) = 0x00029000; // Post processing register
  *((volatile uint32_t *) 0x50d0072c) = 0xffffffff; // Mask and processor enables

  // Layer 8 quadrant 0
  *((volatile uint32_t *) 0x50100030) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50100330) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50100430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005b0) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a30) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100630) = 0x10e01158; // Mask offset and count
  *((volatile uint32_t *) 0x50100130) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x501007b0) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50100730) = 0xffffffff; // Mask and processor enables

  // Layer 8 quadrant 1
  *((volatile uint32_t *) 0x50500030) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50500330) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50500430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005b0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a30) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500630) = 0x10e01158; // Mask offset and count
  *((volatile uint32_t *) 0x50500130) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x505007b0) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50500730) = 0xffffffff; // Mask and processor enables

  // Layer 8 quadrant 2
  *((volatile uint32_t *) 0x50900030) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50900330) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50900430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005b0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a30) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900630) = 0x10e01158; // Mask offset and count
  *((volatile uint32_t *) 0x50900130) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x509007b0) = 0x00023080; // Post processing register
  *((volatile uint32_t *) 0x50900730) = 0xffffffff; // Mask and processor enables

  // Layer 8 quadrant 3
  *((volatile uint32_t *) 0x50d00030) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50d00330) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005b0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a30) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00630) = 0x10e01158; // Mask offset and count
  *((volatile uint32_t *) 0x50d00130) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d007b0) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50d00730) = 0xffffffff; // Mask and processor enables

  // Layer 9 quadrant 0
  *((volatile uint32_t *) 0x50100034) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x50100434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100534) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x501005b4) = 0x00008b20; // Layer control
  *((volatile uint32_t *) 0x50100a34) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100634) = 0x06000678; // Mask offset and count
  *((volatile uint32_t *) 0x50100134) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x501007b4) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50100734) = 0xffffffff; // Mask and processor enables

  // Layer 9 quadrant 1
  *((volatile uint32_t *) 0x50500034) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x50500434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500534) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x505005b4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a34) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500634) = 0x06000678; // Mask offset and count
  *((volatile uint32_t *) 0x50500134) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x505007b4) = 0x00024000; // Post processing register

  // Layer 9 quadrant 2
  *((volatile uint32_t *) 0x50900034) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x50900434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900534) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x509005b4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a34) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900634) = 0x06000678; // Mask offset and count
  *((volatile uint32_t *) 0x50900134) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x509007b4) = 0x00024000; // Post processing register

  // Layer 9 quadrant 3
  *((volatile uint32_t *) 0x50d00034) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x50d00434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00534) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005b4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a34) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00634) = 0x06000678; // Mask offset and count
  *((volatile uint32_t *) 0x50d00134) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50d007b4) = 0x00025080; // Post processing register

  // Layer 10 quadrant 0
  *((volatile uint32_t *) 0x50100038) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50100338) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50100438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005b8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50100a38) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50100638) = 0x14401638; // Mask offset and count
  *((volatile uint32_t *) 0x50100138) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x501007b8) = 0x00025040; // Post processing register
  *((volatile uint32_t *) 0x50100738) = 0xffffffff; // Mask and processor enables

  // Layer 10 quadrant 1
  *((volatile uint32_t *) 0x50500038) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50500338) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50500438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005b8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a38) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50500638) = 0x14401638; // Mask offset and count
  *((volatile uint32_t *) 0x50500138) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x505007b8) = 0x00024000; // Post processing register

  // Layer 10 quadrant 2
  *((volatile uint32_t *) 0x50900038) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50900338) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50900438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005b8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a38) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50900638) = 0x14401638; // Mask offset and count
  *((volatile uint32_t *) 0x50900138) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x509007b8) = 0x00024000; // Post processing register

  // Layer 10 quadrant 3
  *((volatile uint32_t *) 0x50d00038) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50d00338) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005b8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a38) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d00638) = 0x14401638; // Mask offset and count
  *((volatile uint32_t *) 0x50d00138) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d007b8) = 0x00024000; // Post processing register

  // Layer 11 quadrant 0
  *((volatile uint32_t *) 0x5010003c) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x501003bc) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5010053c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x501005bc) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x5010013c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x501007bc) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x5010073c) = 0x0000ffff; // Mask and processor enables

  // Layer 11 quadrant 1
  *((volatile uint32_t *) 0x5050003c) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x5050033c) = 0x00008000; // SRAM write ptr
  *((volatile uint32_t *) 0x505003bc) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5050053c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x505005bc) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x5050013c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x505007bc) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x5050073c) = 0x0000ffff; // Mask and processor enables

  // Layer 11 quadrant 2
  *((volatile uint32_t *) 0x5090003c) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x5090033c) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003bc) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5090053c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x509005bc) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x5090013c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x509007bc) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x5090073c) = 0x0000ffff; // Mask and processor enables

  // Layer 11 quadrant 3
  *((volatile uint32_t *) 0x50d0003c) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50d0033c) = 0x00018000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003bc) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d0053c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005bc) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d0013c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x50d007bc) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50d0073c) = 0x0000ffff; // Mask and processor enables

  // Layer 12 quadrant 0
  *((volatile uint32_t *) 0x50100040) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50100340) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100440) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005c0) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a40) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50100640) = 0x16801878; // Mask offset and count
  *((volatile uint32_t *) 0x50100140) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x501007c0) = 0x00028000; // Post processing register
  *((volatile uint32_t *) 0x50100740) = 0xffffffff; // Mask and processor enables

  // Layer 12 quadrant 1
  *((volatile uint32_t *) 0x50500040) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50500340) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500440) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005c0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a40) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50500640) = 0x16801878; // Mask offset and count
  *((volatile uint32_t *) 0x50500140) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x505007c0) = 0x00029040; // Post processing register
  *((volatile uint32_t *) 0x50500740) = 0xffffffff; // Mask and processor enables

  // Layer 12 quadrant 2
  *((volatile uint32_t *) 0x50900040) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50900340) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900440) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005c0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a40) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50900640) = 0x16801878; // Mask offset and count
  *((volatile uint32_t *) 0x50900140) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x509007c0) = 0x00028000; // Post processing register
  *((volatile uint32_t *) 0x50900740) = 0xffffffff; // Mask and processor enables

  // Layer 12 quadrant 3
  *((volatile uint32_t *) 0x50d00040) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50d00340) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00440) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005c0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a40) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d00640) = 0x16801878; // Mask offset and count
  *((volatile uint32_t *) 0x50d00140) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d007c0) = 0x00028000; // Post processing register
  *((volatile uint32_t *) 0x50d00740) = 0xffffffff; // Mask and processor enables

  // Layer 13 quadrant 0
  *((volatile uint32_t *) 0x50100044) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50100344) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50100444) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005c4) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a44) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100644) = 0x18c01938; // Mask offset and count
  *((volatile uint32_t *) 0x50100144) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x501007c4) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50100744) = 0xffffffff; // Mask and processor enables

  // Layer 13 quadrant 1
  *((volatile uint32_t *) 0x50500044) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50500344) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50500444) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005c4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a44) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500644) = 0x18c01938; // Mask offset and count
  *((volatile uint32_t *) 0x50500144) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x505007c4) = 0x00023090; // Post processing register
  *((volatile uint32_t *) 0x50500744) = 0xffffffff; // Mask and processor enables

  // Layer 13 quadrant 2
  *((volatile uint32_t *) 0x50900044) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50900344) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50900444) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005c4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a44) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900644) = 0x18c01938; // Mask offset and count
  *((volatile uint32_t *) 0x50900144) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x509007c4) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50900744) = 0xffffffff; // Mask and processor enables

  // Layer 13 quadrant 3
  *((volatile uint32_t *) 0x50d00044) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50d00344) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00444) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005c4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a44) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00644) = 0x18c01938; // Mask offset and count
  *((volatile uint32_t *) 0x50d00144) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d007c4) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50d00744) = 0xffffffff; // Mask and processor enables

  // Layer 14 quadrant 0
  *((volatile uint32_t *) 0x50100048) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x50100448) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100548) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x501005c8) = 0x00004b20; // Layer control
  *((volatile uint32_t *) 0x50100a48) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100648) = 0x08a00918; // Mask offset and count
  *((volatile uint32_t *) 0x50100148) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x501007c8) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50100748) = 0xffffffff; // Mask and processor enables

  // Layer 14 quadrant 1
  *((volatile uint32_t *) 0x50500048) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x50500448) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500548) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x505005c8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a48) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500648) = 0x08a00918; // Mask offset and count
  *((volatile uint32_t *) 0x50500148) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x505007c8) = 0x00024000; // Post processing register

  // Layer 14 quadrant 2
  *((volatile uint32_t *) 0x50900048) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x50900448) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900548) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x509005c8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a48) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900648) = 0x08a00918; // Mask offset and count
  *((volatile uint32_t *) 0x50900148) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x509007c8) = 0x00025090; // Post processing register

  // Layer 14 quadrant 3
  *((volatile uint32_t *) 0x50d00048) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x50d00448) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00548) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005c8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a48) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00648) = 0x08a00918; // Mask offset and count
  *((volatile uint32_t *) 0x50d00148) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50d007c8) = 0x00024000; // Post processing register

  // Layer 15 quadrant 0
  *((volatile uint32_t *) 0x5010004c) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x5010034c) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x5010044c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005cc) = 0x00004b20; // Layer control
  *((volatile uint32_t *) 0x50100a4c) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x5010064c) = 0x1c201e18; // Mask offset and count
  *((volatile uint32_t *) 0x5010014c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x501007cc) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x5010074c) = 0xffffffff; // Mask and processor enables

  // Layer 15 quadrant 1
  *((volatile uint32_t *) 0x5050004c) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x5050034c) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x5050044c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005cc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a4c) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x5050064c) = 0x1c201e18; // Mask offset and count
  *((volatile uint32_t *) 0x5050014c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x505007cc) = 0x00022000; // Post processing register

  // Layer 15 quadrant 2
  *((volatile uint32_t *) 0x5090004c) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x5090034c) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x5090044c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005cc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a4c) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x5090064c) = 0x1c201e18; // Mask offset and count
  *((volatile uint32_t *) 0x5090014c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x509007cc) = 0x00023040; // Post processing register

  // Layer 15 quadrant 3
  *((volatile uint32_t *) 0x50d0004c) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50d0034c) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50d0044c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005cc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a4c) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d0064c) = 0x1c201e18; // Mask offset and count
  *((volatile uint32_t *) 0x50d0014c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d007cc) = 0x00022000; // Post processing register

  // Layer 16 quadrant 0
  *((volatile uint32_t *) 0x50100050) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x501003d0) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100550) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x501005d0) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50100150) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x501007d0) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50100750) = 0x0000ffff; // Mask and processor enables

  // Layer 16 quadrant 1
  *((volatile uint32_t *) 0x50500050) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50500350) = 0x00008000; // SRAM write ptr
  *((volatile uint32_t *) 0x505003d0) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500550) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x505005d0) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50500150) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x505007d0) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50500750) = 0x0000ffff; // Mask and processor enables

  // Layer 16 quadrant 2
  *((volatile uint32_t *) 0x50900050) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50900350) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003d0) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900550) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x509005d0) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50900150) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x509007d0) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50900750) = 0x0000ffff; // Mask and processor enables

  // Layer 16 quadrant 3
  *((volatile uint32_t *) 0x50d00050) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50d00350) = 0x00018000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003d0) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00550) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005d0) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d00150) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x50d007d0) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50d00750) = 0x0000ffff; // Mask and processor enables

  // Layer 17 quadrant 0
  *((volatile uint32_t *) 0x50100054) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50100354) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100454) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005d4) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a54) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50100654) = 0x1e602058; // Mask offset and count
  *((volatile uint32_t *) 0x50100154) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x501007d4) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x50100754) = 0xffffffff; // Mask and processor enables

  // Layer 17 quadrant 1
  *((volatile uint32_t *) 0x50500054) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50500354) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500454) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005d4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a54) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50500654) = 0x1e602058; // Mask offset and count
  *((volatile uint32_t *) 0x50500154) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x505007d4) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x50500754) = 0xffffffff; // Mask and processor enables

  // Layer 17 quadrant 2
  *((volatile uint32_t *) 0x50900054) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50900354) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900454) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005d4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a54) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50900654) = 0x1e602058; // Mask offset and count
  *((volatile uint32_t *) 0x50900154) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x509007d4) = 0x00026000; // Post processing register
  *((volatile uint32_t *) 0x50900754) = 0xffffffff; // Mask and processor enables

  // Layer 17 quadrant 3
  *((volatile uint32_t *) 0x50d00054) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50d00354) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00454) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005d4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a54) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d00654) = 0x1e602058; // Mask offset and count
  *((volatile uint32_t *) 0x50d00154) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d007d4) = 0x00027040; // Post processing register
  *((volatile uint32_t *) 0x50d00754) = 0xffffffff; // Mask and processor enables

  // Layer 18 quadrant 0
  *((volatile uint32_t *) 0x50100058) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50100358) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50100458) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005d8) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a58) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100658) = 0x20a02118; // Mask offset and count
  *((volatile uint32_t *) 0x50100158) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x501007d8) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50100758) = 0xffffffff; // Mask and processor enables

  // Layer 18 quadrant 1
  *((volatile uint32_t *) 0x50500058) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50500358) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50500458) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005d8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a58) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500658) = 0x20a02118; // Mask offset and count
  *((volatile uint32_t *) 0x50500158) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x505007d8) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50500758) = 0xffffffff; // Mask and processor enables

  // Layer 18 quadrant 2
  *((volatile uint32_t *) 0x50900058) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50900358) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50900458) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005d8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a58) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900658) = 0x20a02118; // Mask offset and count
  *((volatile uint32_t *) 0x50900158) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x509007d8) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50900758) = 0xffffffff; // Mask and processor enables

  // Layer 18 quadrant 3
  *((volatile uint32_t *) 0x50d00058) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50d00358) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00458) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005d8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a58) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00658) = 0x20a02118; // Mask offset and count
  *((volatile uint32_t *) 0x50d00158) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d007d8) = 0x00025090; // Post processing register
  *((volatile uint32_t *) 0x50d00758) = 0xffffffff; // Mask and processor enables

  // Layer 19 quadrant 0
  *((volatile uint32_t *) 0x5010005c) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x5010045c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5010055c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x501005dc) = 0x00002b20; // Layer control
  *((volatile uint32_t *) 0x50100a5c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5010065c) = 0x0b400bb8; // Mask offset and count
  *((volatile uint32_t *) 0x5010015c) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x501007dc) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x5010075c) = 0xffffffff; // Mask and processor enables

  // Layer 19 quadrant 1
  *((volatile uint32_t *) 0x5050005c) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x5050045c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5050055c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x505005dc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a5c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5050065c) = 0x0b400bb8; // Mask offset and count
  *((volatile uint32_t *) 0x5050015c) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x505007dc) = 0x000230a0; // Post processing register

  // Layer 19 quadrant 2
  *((volatile uint32_t *) 0x5090005c) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x5090045c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5090055c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x509005dc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a5c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5090065c) = 0x0b400bb8; // Mask offset and count
  *((volatile uint32_t *) 0x5090015c) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x509007dc) = 0x00022000; // Post processing register

  // Layer 19 quadrant 3
  *((volatile uint32_t *) 0x50d0005c) = 0x00010019; // Rows
  *((volatile uint32_t *) 0x50d0045c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d0055c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005dc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a5c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d0065c) = 0x0b400bb8; // Mask offset and count
  *((volatile uint32_t *) 0x50d0015c) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50d007dc) = 0x00022000; // Post processing register

  // Layer 20 quadrant 0
  *((volatile uint32_t *) 0x50100060) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50100360) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50100460) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005e0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50100a60) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50100660) = 0x240025f8; // Mask offset and count
  *((volatile uint32_t *) 0x50100160) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x501007e0) = 0x00001080; // Post processing register
  *((volatile uint32_t *) 0x50100760) = 0xffffffff; // Mask and processor enables

  // Layer 20 quadrant 1
  *((volatile uint32_t *) 0x50500060) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50500360) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50500460) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005e0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a60) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50500660) = 0x240025f8; // Mask offset and count
  *((volatile uint32_t *) 0x50500160) = 0x00001100; // 1D

  // Layer 20 quadrant 2
  *((volatile uint32_t *) 0x50900060) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50900360) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50900460) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005e0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a60) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50900660) = 0x240025f8; // Mask offset and count
  *((volatile uint32_t *) 0x50900160) = 0x00001100; // 1D

  // Layer 20 quadrant 3
  *((volatile uint32_t *) 0x50d00060) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50d00360) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00460) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005e0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a60) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d00660) = 0x240025f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00160) = 0x00001100; // 1D

  // Layer 21 quadrant 0
  *((volatile uint32_t *) 0x50100064) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x501003e4) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100564) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x501005e4) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50100164) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x501007e4) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50100764) = 0x0000ffff; // Mask and processor enables

  // Layer 21 quadrant 1
  *((volatile uint32_t *) 0x50500064) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50500364) = 0x00008000; // SRAM write ptr
  *((volatile uint32_t *) 0x505003e4) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500564) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x505005e4) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50500164) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x505007e4) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50500764) = 0x0000ffff; // Mask and processor enables

  // Layer 21 quadrant 2
  *((volatile uint32_t *) 0x50900064) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50900364) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003e4) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900564) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x509005e4) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50900164) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x509007e4) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50900764) = 0x0000ffff; // Mask and processor enables

  // Layer 21 quadrant 3
  *((volatile uint32_t *) 0x50d00064) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50d00364) = 0x00018000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003e4) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00564) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005e4) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d00164) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x50d007e4) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50d00764) = 0x0000ffff; // Mask and processor enables

  // Layer 22 quadrant 0
  *((volatile uint32_t *) 0x50100068) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x501001e8) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x501002e8) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100368) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x501003e8) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x501005e8) = 0x000009a0; // Layer control
  *((volatile uint32_t *) 0x50100168) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x501007e8) = 0x03000000; // Post processing register
  *((volatile uint32_t *) 0x50100768) = 0x0000ffff; // Mask and processor enables

  // Layer 22 quadrant 1
  *((volatile uint32_t *) 0x50500068) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x505001e8) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x505002e8) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500368) = 0x00008800; // SRAM write ptr
  *((volatile uint32_t *) 0x505003e8) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x505005e8) = 0x000009a0; // Layer control
  *((volatile uint32_t *) 0x50500168) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x505007e8) = 0x03000000; // Post processing register
  *((volatile uint32_t *) 0x50500768) = 0x0000ffff; // Mask and processor enables

  // Layer 22 quadrant 2
  *((volatile uint32_t *) 0x50900068) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x509001e8) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x509002e8) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900368) = 0x00010800; // SRAM write ptr
  *((volatile uint32_t *) 0x509003e8) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x509005e8) = 0x000009a0; // Layer control
  *((volatile uint32_t *) 0x50900168) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x509007e8) = 0x03000000; // Post processing register
  *((volatile uint32_t *) 0x50900768) = 0x0000ffff; // Mask and processor enables

  // Layer 22 quadrant 3
  *((volatile uint32_t *) 0x50d00068) = 0x00000017; // Rows
  *((volatile uint32_t *) 0x50d001e8) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d002e8) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00368) = 0x00018800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003e8) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d005e8) = 0x000009a0; // Layer control
  *((volatile uint32_t *) 0x50d00168) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x50d007e8) = 0x03000000; // Post processing register
  *((volatile uint32_t *) 0x50d00768) = 0x0000ffff; // Mask and processor enables

  // Layer 23 quadrant 0
  *((volatile uint32_t *) 0x501003ec) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5010046c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5010056c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x501005ec) = 0x0000e920; // Layer control
  *((volatile uint32_t *) 0x50100a6c) = 0x0000080b; // Layer control 2
  *((volatile uint32_t *) 0x5010066c) = 0x264026f8; // Mask offset and count
  *((volatile uint32_t *) 0x5010016c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x501007ec) = 0x00028000; // Post processing register
  *((volatile uint32_t *) 0x5010076c) = 0xffffffff; // Mask and processor enables

  // Layer 23 quadrant 1
  *((volatile uint32_t *) 0x505003ec) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5050046c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5050056c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x505005ec) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50500a6c) = 0x0000080b; // Layer control 2
  *((volatile uint32_t *) 0x5050066c) = 0x264026f8; // Mask offset and count
  *((volatile uint32_t *) 0x5050016c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x505007ec) = 0x00028000; // Post processing register
  *((volatile uint32_t *) 0x5050076c) = 0xffffffff; // Mask and processor enables

  // Layer 23 quadrant 2
  *((volatile uint32_t *) 0x509003ec) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5090046c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5090056c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x509005ec) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50900a6c) = 0x0000080b; // Layer control 2
  *((volatile uint32_t *) 0x5090066c) = 0x264026f8; // Mask offset and count
  *((volatile uint32_t *) 0x5090016c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x509007ec) = 0x00028000; // Post processing register
  *((volatile uint32_t *) 0x5090076c) = 0xffffffff; // Mask and processor enables

  // Layer 23 quadrant 3
  *((volatile uint32_t *) 0x50d003ec) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d0046c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d0056c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005ec) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d00a6c) = 0x0000080b; // Layer control 2
  *((volatile uint32_t *) 0x50d0066c) = 0x264026f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d0016c) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d007ec) = 0x00028000; // Post processing register
  *((volatile uint32_t *) 0x50d0076c) = 0xffffffff; // Mask and processor enables


  return CNN_OK;
}

int cnn_start(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x50100000) = 0x00100808; // Enable quadrant 0
  *((volatile uint32_t *) 0x50500000) = 0x00100809; // Enable quadrant 1
  *((volatile uint32_t *) 0x50900000) = 0x00100809; // Enable quadrant 2
  *((volatile uint32_t *) 0x50d00000) = 0x00100809; // Enable quadrant 3

#ifdef CNN_INFERENCE_TIMER
  MXC_TMR_SW_Start(CNN_INFERENCE_TIMER);
#endif

  CNN_START; // Allow capture of processing time
  *((volatile uint32_t *) 0x50100000) = 0x00100009; // Master enable quadrant 0

  return CNN_OK;
}

int cnn_unload(uint32_t *out_buf32)
{
  uint8_t *out_buf = (uint8_t *) out_buf32;
  uint32_t val;
  volatile uint32_t *addr;

  // Custom unload for this network, layer 23 (fc): 8-bit data, shape: (2, 1, 1)
  addr = (volatile uint32_t *) 0x50400000;
  val = *addr++;
  *out_buf++ = val & 0xff;
  *out_buf++ = (val >> 8) & 0xff;

  return CNN_OK;
}

int cnn_enable(uint32_t clock_source, uint32_t clock_divider)
{
  // Reset all domains, restore power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg1 = 0xf; // Mask memory
  MXC_GCFR->reg0 = 0xf; // Power
  MXC_GCFR->reg2 = 0x0; // Iso
  MXC_GCFR->reg3 = 0x0; // Reset

  MXC_GCR->pclkdiv = (MXC_GCR->pclkdiv & ~(MXC_F_GCR_PCLKDIV_CNNCLKDIV | MXC_F_GCR_PCLKDIV_CNNCLKSEL))
                     | clock_divider | clock_source;
  MXC_SYS_ClockEnable(MXC_SYS_PERIPH_CLOCK_CNN); // Enable CNN clock

  MXC_NVIC_SetVector(CNN_IRQn, CNN_ISR); // Set CNN complete vector

  return CNN_OK;
}

int cnn_boost_enable(mxc_gpio_regs_t *port, uint32_t pin)
{
  mxc_gpio_cfg_t gpio_out;
  gpio_out.port = port;
  gpio_out.mask = pin;
  gpio_out.pad = MXC_GPIO_PAD_NONE;
  gpio_out.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_out);
  MXC_GPIO_OutSet(gpio_out.port, gpio_out.mask);

  return CNN_OK;
}

int cnn_boost_disable(mxc_gpio_regs_t *port, uint32_t pin)
{
  mxc_gpio_cfg_t gpio_out;
  gpio_out.port = port;
  gpio_out.mask = pin;
  gpio_out.pad = MXC_GPIO_PAD_NONE;
  gpio_out.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_out);
  MXC_GPIO_OutClr(gpio_out.port, gpio_out.mask);

  return CNN_OK;
}

int cnn_disable(void)
{
  // Disable CNN clock
  MXC_SYS_ClockDisable(MXC_SYS_PERIPH_CLOCK_CNN);

  // Disable power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg2 |= 0xf; // Iso
  MXC_GCFR->reg0 = 0x0; // Power
  MXC_GCFR->reg1 = 0x0; // Mask memory
  MXC_GCFR->reg3 = 0x0; // Reset

  return CNN_OK;
}

