/*******************************************************************************
* Copyright (C) 2019-2023 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// RTDemo_MAX_alpha_resnet18
// This file was @generated by ai8xize.py --test-dir synthed_net --prefix RTDemo_MAX_alpha_resnet18 --checkpoint-file trained/resnet18-qat8-q.pth.tar --config-file networks/resnet18.yaml --sample-input tests/sample_kfall.npy --device MAX78000 --board-name FTHR_RevA --compact-data --mexpress --timer 0 --display-checkpoint --verbose --overwrite

// DO NOT EDIT - regenerate this file instead!

// Configuring 29 layers
// Input data: HWC
// Layer 0: 6x50, no pooling, conv1d with kernel size 3, stride 1, pad 0, no activation, 64x48 output
// Layer 1: 64x48, no pooling, conv1d with kernel size 3, stride 1, pad 0, no activation, 64x46 output
// Layer 2: 64x46x1, max pool 2x1 with stride 2/2, no convolution, 64x23x1 output
// Layer 3: 64x23, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 64x23 output
// Layer 4: 64x23, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 16x23 output
// Layer 5: 16x23, no pooling, conv1d with kernel size 3, stride 1, pad 1, ReLU, 16x23 output
// Layer 6: 16x23, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 64x23 output
// Layer 7: 2x64x23x1, no pooling, 2-element add, no convolution, 64x23x1 output
// Layer 8: 64x23, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 64x23 output
// Layer 9: 64x23, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 16x23 output
// Layer 10: 16x23, no pooling, conv1d with kernel size 3, stride 1, pad 1, ReLU, 16x23 output
// Layer 11: 16x23, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 64x23 output
// Layer 12: 2x64x23x1, no pooling, 2-element add, no convolution, 64x23x1 output
// Layer 13: 64x23x1, no pooling, no convolution, 64x23x1 output
// Layer 14: 64x23, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 16x23 output
// Layer 15: 16x23, no pooling, conv1d with kernel size 3, stride 1, pad 1, ReLU, 16x23 output
// Layer 16: 16x23, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 64x23 output
// Layer 17: 2x64x23x1, no pooling, 2-element add, no convolution, 64x23x1 output
// Layer 18: 64x23, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 64x23 output
// Layer 19: 64x23, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 16x23 output
// Layer 20: 16x23, no pooling, conv1d with kernel size 3, stride 1, pad 1, ReLU, 16x23 output
// Layer 21: 16x23, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 64x23 output
// Layer 22: 2x64x23x1, no pooling, 2-element add, no convolution, 64x23x1 output
// Layer 23: 64x23, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 64x23 output
// Layer 24: 64x23, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 16x23 output
// Layer 25: 16x23, no pooling, conv1d with kernel size 3, stride 1, pad 1, ReLU, 16x23 output
// Layer 26: 16x23, no pooling, conv1d with kernel size 1, stride 1, pad 0, ReLU, 64x23 output
// Layer 27: 2x64x23x1, 2-element add, avg pool 2x1 with stride 2/2, no convolution, 64x11x1 output
// Layer 28: 64x11x1 flattened to 704x1x1, no pooling, linear, no activation, 2x1x1 output

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "gcfr_regs.h"
#include "cnn.h"
#include "weights.h"

void CNN_ISR(void)
{
  // Acknowledge interrupt to all quadrants
  *((volatile uint32_t *) 0x50100000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50500000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50900000) &= ~((1<<12) | 1);
  *((volatile uint32_t *) 0x50d00000) &= ~((1<<12) | 1);

  CNN_COMPLETE; // Signal that processing is complete
#ifdef CNN_INFERENCE_TIMER
  cnn_time = MXC_TMR_SW_Stop(CNN_INFERENCE_TIMER);
#else
  cnn_time = 1;
#endif
}

int cnn_continue(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x50100000) |= 1; // Re-enable quadrant 0

  return CNN_OK;
}

int cnn_stop(void)
{
  *((volatile uint32_t *) 0x50100000) &= ~1; // Disable quadrant 0

  return CNN_OK;
}

void memcpy32(uint32_t *dst, const uint32_t *src, int n)
{
  while (n-- > 0) {
    *dst++ = *src++;
  }
}

static const uint32_t kernels[] = KERNELS;

int cnn_load_weights(void)
{
  uint32_t len;
  volatile uint32_t *addr;
  const uint32_t *ptr = kernels;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    *((volatile uint8_t *) ((uint32_t) addr | 1)) = 0x01; // Set address
    len = *ptr++;
    while (len-- > 0)
      *addr++ = *ptr++;
  }

  return CNN_OK;
}

static const uint8_t bias_0[] = BIAS_0;
static const uint8_t bias_1[] = BIAS_1;
static const uint8_t bias_2[] = BIAS_2;
static const uint8_t bias_3[] = BIAS_3;

static void memcpy_8to32(uint32_t *dst, const uint8_t *src, int n)
{
  while (n-- > 0) {
    *dst++ = *src++;
  }
}

int cnn_load_bias(void)
{
  memcpy_8to32((uint32_t *) 0x50108000, bias_0, sizeof(uint8_t) * 224);
  memcpy_8to32((uint32_t *) 0x50508000, bias_1, sizeof(uint8_t) * 224);
  memcpy_8to32((uint32_t *) 0x50908000, bias_2, sizeof(uint8_t) * 208);
  memcpy_8to32((uint32_t *) 0x50d08000, bias_3, sizeof(uint8_t) * 208);

  return CNN_OK;
}

int cnn_init(void)
{
  *((volatile uint32_t *) 0x50001000) = 0x00000000; // AON control
  *((volatile uint32_t *) 0x50100000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50100004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50100008) = 0x0000001c; // Layer count
  *((volatile uint32_t *) 0x50500000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50500004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50500008) = 0x0000001c; // Layer count
  *((volatile uint32_t *) 0x50900000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50900004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50900008) = 0x0000001c; // Layer count
  *((volatile uint32_t *) 0x50d00000) = 0x00100008; // Stop SM
  *((volatile uint32_t *) 0x50d00004) = 0x0000040e; // SRAM control
  *((volatile uint32_t *) 0x50d00008) = 0x0000001c; // Layer count

  return CNN_OK;
}

int cnn_configure(void)
{
  // Layer 0 quadrant 0
  *((volatile uint32_t *) 0x50100010) = 0x00000031; // Rows
  *((volatile uint32_t *) 0x50100310) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50100410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100590) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50100a10) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50100610) = 0x000001f8; // Mask offset and count
  *((volatile uint32_t *) 0x50100110) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50100790) = 0x00023000; // Post processing register
  *((volatile uint32_t *) 0x50100710) = 0x003f003f; // Mask and processor enables

  // Layer 0 quadrant 1
  *((volatile uint32_t *) 0x50500010) = 0x00000031; // Rows
  *((volatile uint32_t *) 0x50500310) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50500410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500590) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50500a10) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50500610) = 0x000001f8; // Mask offset and count
  *((volatile uint32_t *) 0x50500110) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50500790) = 0x00022000; // Post processing register

  // Layer 0 quadrant 2
  *((volatile uint32_t *) 0x50900010) = 0x00000031; // Rows
  *((volatile uint32_t *) 0x50900310) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50900410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900590) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50900a10) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50900610) = 0x000001f8; // Mask offset and count
  *((volatile uint32_t *) 0x50900110) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50900790) = 0x00022000; // Post processing register

  // Layer 0 quadrant 3
  *((volatile uint32_t *) 0x50d00010) = 0x00000031; // Rows
  *((volatile uint32_t *) 0x50d00310) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00410) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00590) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d00a10) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00610) = 0x000001f8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00110) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50d00790) = 0x00022000; // Post processing register

  // Layer 1 quadrant 0
  *((volatile uint32_t *) 0x50100014) = 0x0000002f; // Rows
  *((volatile uint32_t *) 0x50100314) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50100594) = 0x0000e920; // Layer control
  *((volatile uint32_t *) 0x50100a14) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50100614) = 0x02400438; // Mask offset and count
  *((volatile uint32_t *) 0x50100114) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50100794) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50100714) = 0xffffffff; // Mask and processor enables

  // Layer 1 quadrant 1
  *((volatile uint32_t *) 0x50500014) = 0x0000002f; // Rows
  *((volatile uint32_t *) 0x50500314) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50500594) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50500a14) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50500614) = 0x02400438; // Mask offset and count
  *((volatile uint32_t *) 0x50500114) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50500794) = 0x00023000; // Post processing register
  *((volatile uint32_t *) 0x50500714) = 0xffffffff; // Mask and processor enables

  // Layer 1 quadrant 2
  *((volatile uint32_t *) 0x50900014) = 0x0000002f; // Rows
  *((volatile uint32_t *) 0x50900314) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50900594) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50900a14) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50900614) = 0x02400438; // Mask offset and count
  *((volatile uint32_t *) 0x50900114) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50900794) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50900714) = 0xffffffff; // Mask and processor enables

  // Layer 1 quadrant 3
  *((volatile uint32_t *) 0x50d00014) = 0x0000002f; // Rows
  *((volatile uint32_t *) 0x50d00314) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00414) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00514) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d00594) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d00a14) = 0x0001f800; // Layer control 2
  *((volatile uint32_t *) 0x50d00614) = 0x02400438; // Mask offset and count
  *((volatile uint32_t *) 0x50d00114) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50d00794) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50d00714) = 0xffffffff; // Mask and processor enables

  // Layer 2 quadrant 0
  *((volatile uint32_t *) 0x50100018) = 0x0000002d; // Rows
  *((volatile uint32_t *) 0x50100198) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50100298) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50100398) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100518) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50100598) = 0x000009a0; // Layer control
  *((volatile uint32_t *) 0x50100118) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x50100798) = 0x03000000; // Post processing register
  *((volatile uint32_t *) 0x50100718) = 0x0000ffff; // Mask and processor enables

  // Layer 2 quadrant 1
  *((volatile uint32_t *) 0x50500018) = 0x0000002d; // Rows
  *((volatile uint32_t *) 0x50500198) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50500298) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50500318) = 0x00008000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500398) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500518) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50500598) = 0x000009a0; // Layer control
  *((volatile uint32_t *) 0x50500118) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x50500798) = 0x03000000; // Post processing register
  *((volatile uint32_t *) 0x50500718) = 0x0000ffff; // Mask and processor enables

  // Layer 2 quadrant 2
  *((volatile uint32_t *) 0x50900018) = 0x0000002d; // Rows
  *((volatile uint32_t *) 0x50900198) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50900298) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50900318) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900398) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900518) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50900598) = 0x000009a0; // Layer control
  *((volatile uint32_t *) 0x50900118) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x50900798) = 0x03000000; // Post processing register
  *((volatile uint32_t *) 0x50900718) = 0x0000ffff; // Mask and processor enables

  // Layer 2 quadrant 3
  *((volatile uint32_t *) 0x50d00018) = 0x0000002d; // Rows
  *((volatile uint32_t *) 0x50d00198) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d00298) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d00318) = 0x00018000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00398) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00518) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d00598) = 0x000009a0; // Layer control
  *((volatile uint32_t *) 0x50d00118) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x50d00798) = 0x03000000; // Post processing register
  *((volatile uint32_t *) 0x50d00718) = 0x0000ffff; // Mask and processor enables

  // Layer 3 quadrant 0
  *((volatile uint32_t *) 0x5010001c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x5010031c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x5010041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5010059c) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a1c) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x5010061c) = 0x0d800f78; // Mask offset and count
  *((volatile uint32_t *) 0x5010011c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x5010079c) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x5010071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 1
  *((volatile uint32_t *) 0x5050001c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x5050031c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x5050041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5050059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a1c) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x5050061c) = 0x0d800f78; // Mask offset and count
  *((volatile uint32_t *) 0x5050011c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x5050079c) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x5050071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 2
  *((volatile uint32_t *) 0x5090001c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x5090031c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x5090041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5090059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a1c) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x5090061c) = 0x0d800f78; // Mask offset and count
  *((volatile uint32_t *) 0x5090011c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x5090079c) = 0x00023000; // Post processing register
  *((volatile uint32_t *) 0x5090071c) = 0xffffffff; // Mask and processor enables

  // Layer 3 quadrant 3
  *((volatile uint32_t *) 0x50d0001c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50d0031c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d0041c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d0059c) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a1c) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d0061c) = 0x0d800f78; // Mask offset and count
  *((volatile uint32_t *) 0x50d0011c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d0079c) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50d0071c) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 0
  *((volatile uint32_t *) 0x50100020) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50100320) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50100420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005a0) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a20) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100620) = 0x0fc01038; // Mask offset and count
  *((volatile uint32_t *) 0x50100120) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x501007a0) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50100720) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 1
  *((volatile uint32_t *) 0x50500020) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50500320) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50500420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005a0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a20) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500620) = 0x0fc01038; // Mask offset and count
  *((volatile uint32_t *) 0x50500120) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x505007a0) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50500720) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 2
  *((volatile uint32_t *) 0x50900020) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50900320) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50900420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005a0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a20) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900620) = 0x0fc01038; // Mask offset and count
  *((volatile uint32_t *) 0x50900120) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x509007a0) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50900720) = 0xffffffff; // Mask and processor enables

  // Layer 4 quadrant 3
  *((volatile uint32_t *) 0x50d00020) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50d00320) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00420) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005a0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a20) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00620) = 0x0fc01038; // Mask offset and count
  *((volatile uint32_t *) 0x50d00120) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d007a0) = 0x00025080; // Post processing register
  *((volatile uint32_t *) 0x50d00720) = 0xffffffff; // Mask and processor enables

  // Layer 5 quadrant 0
  *((volatile uint32_t *) 0x50100024) = 0x00010018; // Rows
  *((volatile uint32_t *) 0x50100424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100524) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x501005a4) = 0x00008b20; // Layer control
  *((volatile uint32_t *) 0x50100a24) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100624) = 0x05a00618; // Mask offset and count
  *((volatile uint32_t *) 0x50100124) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50100724) = 0xffffffff; // Mask and processor enables

  // Layer 5 quadrant 1
  *((volatile uint32_t *) 0x50500024) = 0x00010018; // Rows
  *((volatile uint32_t *) 0x50500424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500524) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x505005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a24) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500624) = 0x05a00618; // Mask offset and count
  *((volatile uint32_t *) 0x50500124) = 0x00001300; // 1D

  // Layer 5 quadrant 2
  *((volatile uint32_t *) 0x50900024) = 0x00010018; // Rows
  *((volatile uint32_t *) 0x50900424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900524) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x509005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a24) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900624) = 0x05a00618; // Mask offset and count
  *((volatile uint32_t *) 0x50900124) = 0x00001300; // 1D

  // Layer 5 quadrant 3
  *((volatile uint32_t *) 0x50d00024) = 0x00010018; // Rows
  *((volatile uint32_t *) 0x50d00424) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00524) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005a4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a24) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00624) = 0x05a00618; // Mask offset and count
  *((volatile uint32_t *) 0x50d00124) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50d007a4) = 0x00001090; // Post processing register

  // Layer 6 quadrant 0
  *((volatile uint32_t *) 0x50100028) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50100328) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50100428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005a8) = 0x00008b20; // Layer control
  *((volatile uint32_t *) 0x50100a28) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50100628) = 0x13201518; // Mask offset and count
  *((volatile uint32_t *) 0x50100128) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x501007a8) = 0x00002000; // Post processing register
  *((volatile uint32_t *) 0x50100728) = 0xffffffff; // Mask and processor enables

  // Layer 6 quadrant 1
  *((volatile uint32_t *) 0x50500028) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50500328) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50500428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005a8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a28) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50500628) = 0x13201518; // Mask offset and count
  *((volatile uint32_t *) 0x50500128) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x505007a8) = 0x00002000; // Post processing register

  // Layer 6 quadrant 2
  *((volatile uint32_t *) 0x50900028) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50900328) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50900428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005a8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a28) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50900628) = 0x13201518; // Mask offset and count
  *((volatile uint32_t *) 0x50900128) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x509007a8) = 0x00002000; // Post processing register

  // Layer 6 quadrant 3
  *((volatile uint32_t *) 0x50d00028) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50d00328) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00428) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005a8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a28) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d00628) = 0x13201518; // Mask offset and count
  *((volatile uint32_t *) 0x50d00128) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d007a8) = 0x00003000; // Post processing register

  // Layer 7 quadrant 0
  *((volatile uint32_t *) 0x5010002c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x501003ac) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5010052c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x501005ac) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x5010012c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x501007ac) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x5010072c) = 0x0000ffff; // Mask and processor enables

  // Layer 7 quadrant 1
  *((volatile uint32_t *) 0x5050002c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x5050032c) = 0x00008000; // SRAM write ptr
  *((volatile uint32_t *) 0x505003ac) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5050052c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x505005ac) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x5050012c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x505007ac) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x5050072c) = 0x0000ffff; // Mask and processor enables

  // Layer 7 quadrant 2
  *((volatile uint32_t *) 0x5090002c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x5090032c) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003ac) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5090052c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x509005ac) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x5090012c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x509007ac) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x5090072c) = 0x0000ffff; // Mask and processor enables

  // Layer 7 quadrant 3
  *((volatile uint32_t *) 0x50d0002c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50d0032c) = 0x00018000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003ac) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d0052c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005ac) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d0012c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x50d007ac) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50d0072c) = 0x0000ffff; // Mask and processor enables

  // Layer 8 quadrant 0
  *((volatile uint32_t *) 0x50100030) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50100330) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005b0) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a30) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50100630) = 0x15601758; // Mask offset and count
  *((volatile uint32_t *) 0x50100130) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x501007b0) = 0x00023040; // Post processing register
  *((volatile uint32_t *) 0x50100730) = 0xffffffff; // Mask and processor enables

  // Layer 8 quadrant 1
  *((volatile uint32_t *) 0x50500030) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50500330) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005b0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a30) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50500630) = 0x15601758; // Mask offset and count
  *((volatile uint32_t *) 0x50500130) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x505007b0) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50500730) = 0xffffffff; // Mask and processor enables

  // Layer 8 quadrant 2
  *((volatile uint32_t *) 0x50900030) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50900330) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005b0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a30) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50900630) = 0x15601758; // Mask offset and count
  *((volatile uint32_t *) 0x50900130) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x509007b0) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50900730) = 0xffffffff; // Mask and processor enables

  // Layer 8 quadrant 3
  *((volatile uint32_t *) 0x50d00030) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50d00330) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00430) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005b0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a30) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d00630) = 0x15601758; // Mask offset and count
  *((volatile uint32_t *) 0x50d00130) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d007b0) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50d00730) = 0xffffffff; // Mask and processor enables

  // Layer 9 quadrant 0
  *((volatile uint32_t *) 0x50100034) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50100334) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50100434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005b4) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a34) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100634) = 0x17a01818; // Mask offset and count
  *((volatile uint32_t *) 0x50100134) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50100734) = 0xffffffff; // Mask and processor enables

  // Layer 9 quadrant 1
  *((volatile uint32_t *) 0x50500034) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50500334) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50500434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005b4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a34) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500634) = 0x17a01818; // Mask offset and count
  *((volatile uint32_t *) 0x50500134) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50500734) = 0xffffffff; // Mask and processor enables

  // Layer 9 quadrant 2
  *((volatile uint32_t *) 0x50900034) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50900334) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50900434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005b4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a34) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900634) = 0x17a01818; // Mask offset and count
  *((volatile uint32_t *) 0x50900134) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50900734) = 0xffffffff; // Mask and processor enables

  // Layer 9 quadrant 3
  *((volatile uint32_t *) 0x50d00034) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50d00334) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00434) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005b4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a34) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00634) = 0x17a01818; // Mask offset and count
  *((volatile uint32_t *) 0x50d00134) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d007b4) = 0x000010a0; // Post processing register
  *((volatile uint32_t *) 0x50d00734) = 0xffffffff; // Mask and processor enables

  // Layer 10 quadrant 0
  *((volatile uint32_t *) 0x50100038) = 0x00010018; // Rows
  *((volatile uint32_t *) 0x50100438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100538) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x501005b8) = 0x00008b20; // Layer control
  *((volatile uint32_t *) 0x50100a38) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100638) = 0x084008b8; // Mask offset and count
  *((volatile uint32_t *) 0x50100138) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50100738) = 0xffffffff; // Mask and processor enables

  // Layer 10 quadrant 1
  *((volatile uint32_t *) 0x50500038) = 0x00010018; // Rows
  *((volatile uint32_t *) 0x50500438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500538) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x505005b8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a38) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500638) = 0x084008b8; // Mask offset and count
  *((volatile uint32_t *) 0x50500138) = 0x00001300; // 1D

  // Layer 10 quadrant 2
  *((volatile uint32_t *) 0x50900038) = 0x00010018; // Rows
  *((volatile uint32_t *) 0x50900438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900538) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x509005b8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a38) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900638) = 0x084008b8; // Mask offset and count
  *((volatile uint32_t *) 0x50900138) = 0x00001300; // 1D

  // Layer 10 quadrant 3
  *((volatile uint32_t *) 0x50d00038) = 0x00010018; // Rows
  *((volatile uint32_t *) 0x50d00438) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00538) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005b8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a38) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00638) = 0x084008b8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00138) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50d007b8) = 0x000010b0; // Post processing register

  // Layer 11 quadrant 0
  *((volatile uint32_t *) 0x5010003c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x5010033c) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x5010043c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005bc) = 0x00002b20; // Layer control
  *((volatile uint32_t *) 0x50100a3c) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x5010063c) = 0x1b001cf8; // Mask offset and count
  *((volatile uint32_t *) 0x5010013c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x501007bc) = 0x00002000; // Post processing register
  *((volatile uint32_t *) 0x5010073c) = 0xffffffff; // Mask and processor enables

  // Layer 11 quadrant 1
  *((volatile uint32_t *) 0x5050003c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x5050033c) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x5050043c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005bc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a3c) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x5050063c) = 0x1b001cf8; // Mask offset and count
  *((volatile uint32_t *) 0x5050013c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x505007bc) = 0x00003040; // Post processing register

  // Layer 11 quadrant 2
  *((volatile uint32_t *) 0x5090003c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x5090033c) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x5090043c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005bc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a3c) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x5090063c) = 0x1b001cf8; // Mask offset and count
  *((volatile uint32_t *) 0x5090013c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x509007bc) = 0x00002000; // Post processing register

  // Layer 11 quadrant 3
  *((volatile uint32_t *) 0x50d0003c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50d0033c) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50d0043c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005bc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a3c) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d0063c) = 0x1b001cf8; // Mask offset and count
  *((volatile uint32_t *) 0x50d0013c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d007bc) = 0x00002000; // Post processing register

  // Layer 12 quadrant 0
  *((volatile uint32_t *) 0x50100040) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x501003c0) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100540) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x501005c0) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50100140) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x501007c0) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50100740) = 0x0000ffff; // Mask and processor enables

  // Layer 12 quadrant 1
  *((volatile uint32_t *) 0x50500040) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50500340) = 0x00008000; // SRAM write ptr
  *((volatile uint32_t *) 0x505003c0) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500540) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x505005c0) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50500140) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x505007c0) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50500740) = 0x0000ffff; // Mask and processor enables

  // Layer 12 quadrant 2
  *((volatile uint32_t *) 0x50900040) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50900340) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003c0) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900540) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x509005c0) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50900140) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x509007c0) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50900740) = 0x0000ffff; // Mask and processor enables

  // Layer 12 quadrant 3
  *((volatile uint32_t *) 0x50d00040) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50d00340) = 0x00018000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003c0) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00540) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005c0) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d00140) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x50d007c0) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50d00740) = 0x0000ffff; // Mask and processor enables

  // Layer 13 quadrant 0
  *((volatile uint32_t *) 0x50100044) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50100344) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x501003c4) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x501005c4) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50100a44) = 0x00000010; // Layer control 2
  *((volatile uint32_t *) 0x50100144) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x501007c4) = 0x03000000; // Post processing register
  *((volatile uint32_t *) 0x50100744) = 0x0000ffff; // Mask and processor enables

  // Layer 13 quadrant 1
  *((volatile uint32_t *) 0x50500044) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50500344) = 0x00009000; // SRAM write ptr
  *((volatile uint32_t *) 0x505003c4) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x505005c4) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50500a44) = 0x00000010; // Layer control 2
  *((volatile uint32_t *) 0x50500144) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x505007c4) = 0x03000000; // Post processing register
  *((volatile uint32_t *) 0x50500744) = 0x0000ffff; // Mask and processor enables

  // Layer 13 quadrant 2
  *((volatile uint32_t *) 0x50900044) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50900344) = 0x00011000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003c4) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x509005c4) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50900a44) = 0x00000010; // Layer control 2
  *((volatile uint32_t *) 0x50900144) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x509007c4) = 0x03000000; // Post processing register
  *((volatile uint32_t *) 0x50900744) = 0x0000ffff; // Mask and processor enables

  // Layer 13 quadrant 3
  *((volatile uint32_t *) 0x50d00044) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50d00344) = 0x00019000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003c4) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d005c4) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d00a44) = 0x00000010; // Layer control 2
  *((volatile uint32_t *) 0x50d00144) = 0x00000103; // 1D
  *((volatile uint32_t *) 0x50d007c4) = 0x03000000; // Post processing register
  *((volatile uint32_t *) 0x50d00744) = 0x0000ffff; // Mask and processor enables

  // Layer 14 quadrant 0
  *((volatile uint32_t *) 0x50100048) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50100348) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50100448) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005c8) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a48) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100648) = 0x1d401db8; // Mask offset and count
  *((volatile uint32_t *) 0x50100148) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x501007c8) = 0x000230c0; // Post processing register
  *((volatile uint32_t *) 0x50100748) = 0xffffffff; // Mask and processor enables

  // Layer 14 quadrant 1
  *((volatile uint32_t *) 0x50500048) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50500348) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50500448) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005c8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a48) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500648) = 0x1d401db8; // Mask offset and count
  *((volatile uint32_t *) 0x50500148) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x505007c8) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50500748) = 0xffffffff; // Mask and processor enables

  // Layer 14 quadrant 2
  *((volatile uint32_t *) 0x50900048) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50900348) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50900448) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005c8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a48) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900648) = 0x1d401db8; // Mask offset and count
  *((volatile uint32_t *) 0x50900148) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x509007c8) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50900748) = 0xffffffff; // Mask and processor enables

  // Layer 14 quadrant 3
  *((volatile uint32_t *) 0x50d00048) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50d00348) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00448) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005c8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a48) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00648) = 0x1d401db8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00148) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d007c8) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50d00748) = 0xffffffff; // Mask and processor enables

  // Layer 15 quadrant 0
  *((volatile uint32_t *) 0x5010004c) = 0x00010018; // Rows
  *((volatile uint32_t *) 0x5010044c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5010054c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x501005cc) = 0x00002b20; // Layer control
  *((volatile uint32_t *) 0x50100a4c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5010064c) = 0x0a200a98; // Mask offset and count
  *((volatile uint32_t *) 0x5010014c) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x501007cc) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x5010074c) = 0xffffffff; // Mask and processor enables

  // Layer 15 quadrant 1
  *((volatile uint32_t *) 0x5050004c) = 0x00010018; // Rows
  *((volatile uint32_t *) 0x5050044c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5050054c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x505005cc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a4c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5050064c) = 0x0a200a98; // Mask offset and count
  *((volatile uint32_t *) 0x5050014c) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x505007cc) = 0x000230c0; // Post processing register

  // Layer 15 quadrant 2
  *((volatile uint32_t *) 0x5090004c) = 0x00010018; // Rows
  *((volatile uint32_t *) 0x5090044c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x5090054c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x509005cc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a4c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5090064c) = 0x0a200a98; // Mask offset and count
  *((volatile uint32_t *) 0x5090014c) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x509007cc) = 0x00022000; // Post processing register

  // Layer 15 quadrant 3
  *((volatile uint32_t *) 0x50d0004c) = 0x00010018; // Rows
  *((volatile uint32_t *) 0x50d0044c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d0054c) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005cc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a4c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d0064c) = 0x0a200a98; // Mask offset and count
  *((volatile uint32_t *) 0x50d0014c) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50d007cc) = 0x00022000; // Post processing register

  // Layer 16 quadrant 0
  *((volatile uint32_t *) 0x50100050) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50100350) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50100450) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005d0) = 0x00004b20; // Layer control
  *((volatile uint32_t *) 0x50100a50) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50100650) = 0x20a02298; // Mask offset and count
  *((volatile uint32_t *) 0x50100150) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50100750) = 0xffffffff; // Mask and processor enables

  // Layer 16 quadrant 1
  *((volatile uint32_t *) 0x50500050) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50500350) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50500450) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005d0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a50) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50500650) = 0x20a02298; // Mask offset and count
  *((volatile uint32_t *) 0x50500150) = 0x00001100; // 1D

  // Layer 16 quadrant 2
  *((volatile uint32_t *) 0x50900050) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50900350) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50900450) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005d0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a50) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50900650) = 0x20a02298; // Mask offset and count
  *((volatile uint32_t *) 0x50900150) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x509007d0) = 0x00001040; // Post processing register

  // Layer 16 quadrant 3
  *((volatile uint32_t *) 0x50d00050) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50d00350) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00450) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005d0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a50) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d00650) = 0x20a02298; // Mask offset and count
  *((volatile uint32_t *) 0x50d00150) = 0x00001100; // 1D

  // Layer 17 quadrant 0
  *((volatile uint32_t *) 0x50100054) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x501003d4) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100554) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x501005d4) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50100154) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x501007d4) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50100754) = 0x0000ffff; // Mask and processor enables

  // Layer 17 quadrant 1
  *((volatile uint32_t *) 0x50500054) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50500354) = 0x00008000; // SRAM write ptr
  *((volatile uint32_t *) 0x505003d4) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500554) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x505005d4) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50500154) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x505007d4) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50500754) = 0x0000ffff; // Mask and processor enables

  // Layer 17 quadrant 2
  *((volatile uint32_t *) 0x50900054) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50900354) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003d4) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900554) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x509005d4) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50900154) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x509007d4) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50900754) = 0x0000ffff; // Mask and processor enables

  // Layer 17 quadrant 3
  *((volatile uint32_t *) 0x50d00054) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50d00354) = 0x00018000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003d4) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00554) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005d4) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d00154) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x50d007d4) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50d00754) = 0x0000ffff; // Mask and processor enables

  // Layer 18 quadrant 0
  *((volatile uint32_t *) 0x50100058) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50100358) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50100458) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005d8) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a58) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50100658) = 0x22e024d8; // Mask offset and count
  *((volatile uint32_t *) 0x50100158) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x501007d8) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50100758) = 0xffffffff; // Mask and processor enables

  // Layer 18 quadrant 1
  *((volatile uint32_t *) 0x50500058) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50500358) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50500458) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005d8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a58) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50500658) = 0x22e024d8; // Mask offset and count
  *((volatile uint32_t *) 0x50500158) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x505007d8) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50500758) = 0xffffffff; // Mask and processor enables

  // Layer 18 quadrant 2
  *((volatile uint32_t *) 0x50900058) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50900358) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50900458) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005d8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a58) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50900658) = 0x22e024d8; // Mask offset and count
  *((volatile uint32_t *) 0x50900158) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x509007d8) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50900758) = 0xffffffff; // Mask and processor enables

  // Layer 18 quadrant 3
  *((volatile uint32_t *) 0x50d00058) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50d00358) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00458) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005d8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a58) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d00658) = 0x22e024d8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00158) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d007d8) = 0x00025040; // Post processing register
  *((volatile uint32_t *) 0x50d00758) = 0xffffffff; // Mask and processor enables

  // Layer 19 quadrant 0
  *((volatile uint32_t *) 0x5010005c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x5010035c) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x5010045c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005dc) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a5c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5010065c) = 0x25202598; // Mask offset and count
  *((volatile uint32_t *) 0x5010015c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x5010075c) = 0xffffffff; // Mask and processor enables

  // Layer 19 quadrant 1
  *((volatile uint32_t *) 0x5050005c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x5050035c) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x5050045c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005dc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a5c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5050065c) = 0x25202598; // Mask offset and count
  *((volatile uint32_t *) 0x5050015c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x5050075c) = 0xffffffff; // Mask and processor enables

  // Layer 19 quadrant 2
  *((volatile uint32_t *) 0x5090005c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x5090035c) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x5090045c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005dc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a5c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x5090065c) = 0x25202598; // Mask offset and count
  *((volatile uint32_t *) 0x5090015c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x509007dc) = 0x000010c0; // Post processing register
  *((volatile uint32_t *) 0x5090075c) = 0xffffffff; // Mask and processor enables

  // Layer 19 quadrant 3
  *((volatile uint32_t *) 0x50d0005c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50d0035c) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d0045c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005dc) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a5c) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d0065c) = 0x25202598; // Mask offset and count
  *((volatile uint32_t *) 0x50d0015c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d0075c) = 0xffffffff; // Mask and processor enables

  // Layer 20 quadrant 0
  *((volatile uint32_t *) 0x50100060) = 0x00010018; // Rows
  *((volatile uint32_t *) 0x50100460) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100560) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x501005e0) = 0x00008b20; // Layer control
  *((volatile uint32_t *) 0x50100a60) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100660) = 0x0cc00d38; // Mask offset and count
  *((volatile uint32_t *) 0x50100160) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50100760) = 0xffffffff; // Mask and processor enables

  // Layer 20 quadrant 1
  *((volatile uint32_t *) 0x50500060) = 0x00010018; // Rows
  *((volatile uint32_t *) 0x50500460) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500560) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x505005e0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a60) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500660) = 0x0cc00d38; // Mask offset and count
  *((volatile uint32_t *) 0x50500160) = 0x00001300; // 1D

  // Layer 20 quadrant 2
  *((volatile uint32_t *) 0x50900060) = 0x00010018; // Rows
  *((volatile uint32_t *) 0x50900460) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900560) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x509005e0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a60) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900660) = 0x0cc00d38; // Mask offset and count
  *((volatile uint32_t *) 0x50900160) = 0x00001300; // 1D

  // Layer 20 quadrant 3
  *((volatile uint32_t *) 0x50d00060) = 0x00010018; // Rows
  *((volatile uint32_t *) 0x50d00460) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00560) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005e0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a60) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00660) = 0x0cc00d38; // Mask offset and count
  *((volatile uint32_t *) 0x50d00160) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50d007e0) = 0x000010c0; // Post processing register

  // Layer 21 quadrant 0
  *((volatile uint32_t *) 0x50100064) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50100364) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50100464) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005e4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50100a64) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50100664) = 0x28802a78; // Mask offset and count
  *((volatile uint32_t *) 0x50100164) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x501007e4) = 0x00003080; // Post processing register
  *((volatile uint32_t *) 0x50100764) = 0xffffffff; // Mask and processor enables

  // Layer 21 quadrant 1
  *((volatile uint32_t *) 0x50500064) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50500364) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50500464) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005e4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a64) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50500664) = 0x28802a78; // Mask offset and count
  *((volatile uint32_t *) 0x50500164) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x505007e4) = 0x00002000; // Post processing register

  // Layer 21 quadrant 2
  *((volatile uint32_t *) 0x50900064) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50900364) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50900464) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005e4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a64) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50900664) = 0x28802a78; // Mask offset and count
  *((volatile uint32_t *) 0x50900164) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x509007e4) = 0x00002000; // Post processing register

  // Layer 21 quadrant 3
  *((volatile uint32_t *) 0x50d00064) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50d00364) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00464) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005e4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a64) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d00664) = 0x28802a78; // Mask offset and count
  *((volatile uint32_t *) 0x50d00164) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d007e4) = 0x00002000; // Post processing register

  // Layer 22 quadrant 0
  *((volatile uint32_t *) 0x50100068) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x501003e8) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100568) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x501005e8) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50100168) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x501007e8) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50100768) = 0x0000ffff; // Mask and processor enables

  // Layer 22 quadrant 1
  *((volatile uint32_t *) 0x50500068) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50500368) = 0x00008000; // SRAM write ptr
  *((volatile uint32_t *) 0x505003e8) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500568) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x505005e8) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50500168) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x505007e8) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50500768) = 0x0000ffff; // Mask and processor enables

  // Layer 22 quadrant 2
  *((volatile uint32_t *) 0x50900068) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50900368) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003e8) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900568) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x509005e8) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50900168) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x509007e8) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50900768) = 0x0000ffff; // Mask and processor enables

  // Layer 22 quadrant 3
  *((volatile uint32_t *) 0x50d00068) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50d00368) = 0x00018000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003e8) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00568) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005e8) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d00168) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x50d007e8) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50d00768) = 0x0000ffff; // Mask and processor enables

  // Layer 23 quadrant 0
  *((volatile uint32_t *) 0x5010006c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x5010036c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x5010046c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005ec) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a6c) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x5010066c) = 0x2ac02cb8; // Mask offset and count
  *((volatile uint32_t *) 0x5010016c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x501007ec) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x5010076c) = 0xffffffff; // Mask and processor enables

  // Layer 23 quadrant 1
  *((volatile uint32_t *) 0x5050006c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x5050036c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x5050046c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005ec) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a6c) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x5050066c) = 0x2ac02cb8; // Mask offset and count
  *((volatile uint32_t *) 0x5050016c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x505007ec) = 0x00025080; // Post processing register
  *((volatile uint32_t *) 0x5050076c) = 0xffffffff; // Mask and processor enables

  // Layer 23 quadrant 2
  *((volatile uint32_t *) 0x5090006c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x5090036c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x5090046c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005ec) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a6c) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x5090066c) = 0x2ac02cb8; // Mask offset and count
  *((volatile uint32_t *) 0x5090016c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x509007ec) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x5090076c) = 0xffffffff; // Mask and processor enables

  // Layer 23 quadrant 3
  *((volatile uint32_t *) 0x50d0006c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50d0036c) = 0x00001000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d0046c) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005ec) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a6c) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d0066c) = 0x2ac02cb8; // Mask offset and count
  *((volatile uint32_t *) 0x50d0016c) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d007ec) = 0x00024000; // Post processing register
  *((volatile uint32_t *) 0x50d0076c) = 0xffffffff; // Mask and processor enables

  // Layer 24 quadrant 0
  *((volatile uint32_t *) 0x50100070) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50100370) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50100470) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005f0) = 0x0000eb20; // Layer control
  *((volatile uint32_t *) 0x50100a70) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100670) = 0x2d002d78; // Mask offset and count
  *((volatile uint32_t *) 0x50100170) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x501007f0) = 0x000230d0; // Post processing register
  *((volatile uint32_t *) 0x50100770) = 0xffffffff; // Mask and processor enables

  // Layer 24 quadrant 1
  *((volatile uint32_t *) 0x50500070) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50500370) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50500470) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005f0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a70) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500670) = 0x2d002d78; // Mask offset and count
  *((volatile uint32_t *) 0x50500170) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x505007f0) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50500770) = 0xffffffff; // Mask and processor enables

  // Layer 24 quadrant 2
  *((volatile uint32_t *) 0x50900070) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50900370) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50900470) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005f0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a70) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900670) = 0x2d002d78; // Mask offset and count
  *((volatile uint32_t *) 0x50900170) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x509007f0) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50900770) = 0xffffffff; // Mask and processor enables

  // Layer 24 quadrant 3
  *((volatile uint32_t *) 0x50d00070) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50d00370) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00470) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005f0) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a70) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00670) = 0x2d002d78; // Mask offset and count
  *((volatile uint32_t *) 0x50d00170) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d007f0) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50d00770) = 0xffffffff; // Mask and processor enables

  // Layer 25 quadrant 0
  *((volatile uint32_t *) 0x50100074) = 0x00010018; // Rows
  *((volatile uint32_t *) 0x50100474) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100574) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x501005f4) = 0x00002b20; // Layer control
  *((volatile uint32_t *) 0x50100a74) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50100674) = 0x0f600fd8; // Mask offset and count
  *((volatile uint32_t *) 0x50100174) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x501007f4) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50100774) = 0xffffffff; // Mask and processor enables

  // Layer 25 quadrant 1
  *((volatile uint32_t *) 0x50500074) = 0x00010018; // Rows
  *((volatile uint32_t *) 0x50500474) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500574) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x505005f4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a74) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50500674) = 0x0f600fd8; // Mask offset and count
  *((volatile uint32_t *) 0x50500174) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x505007f4) = 0x000230d0; // Post processing register

  // Layer 25 quadrant 2
  *((volatile uint32_t *) 0x50900074) = 0x00010018; // Rows
  *((volatile uint32_t *) 0x50900474) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900574) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x509005f4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a74) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50900674) = 0x0f600fd8; // Mask offset and count
  *((volatile uint32_t *) 0x50900174) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x509007f4) = 0x00022000; // Post processing register

  // Layer 25 quadrant 3
  *((volatile uint32_t *) 0x50d00074) = 0x00010018; // Rows
  *((volatile uint32_t *) 0x50d00474) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00574) = 0x00000800; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005f4) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a74) = 0x00007800; // Layer control 2
  *((volatile uint32_t *) 0x50d00674) = 0x0f600fd8; // Mask offset and count
  *((volatile uint32_t *) 0x50d00174) = 0x00001300; // 1D
  *((volatile uint32_t *) 0x50d007f4) = 0x00022000; // Post processing register

  // Layer 26 quadrant 0
  *((volatile uint32_t *) 0x50100078) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50100378) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50100478) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x501005f8) = 0x00004b20; // Layer control
  *((volatile uint32_t *) 0x50100a78) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50100678) = 0x30603258; // Mask offset and count
  *((volatile uint32_t *) 0x50100178) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x501007f8) = 0x00002000; // Post processing register
  *((volatile uint32_t *) 0x50100778) = 0xffffffff; // Mask and processor enables

  // Layer 26 quadrant 1
  *((volatile uint32_t *) 0x50500078) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50500378) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50500478) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x505005f8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50500a78) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50500678) = 0x30603258; // Mask offset and count
  *((volatile uint32_t *) 0x50500178) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x505007f8) = 0x00002000; // Post processing register

  // Layer 26 quadrant 2
  *((volatile uint32_t *) 0x50900078) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50900378) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50900478) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x509005f8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50900a78) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50900678) = 0x30603258; // Mask offset and count
  *((volatile uint32_t *) 0x50900178) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x509007f8) = 0x00003080; // Post processing register

  // Layer 26 quadrant 3
  *((volatile uint32_t *) 0x50d00078) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50d00378) = 0x00001001; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00478) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d005f8) = 0x00000b20; // Layer control
  *((volatile uint32_t *) 0x50d00a78) = 0x0001f810; // Layer control 2
  *((volatile uint32_t *) 0x50d00678) = 0x30603258; // Mask offset and count
  *((volatile uint32_t *) 0x50d00178) = 0x00001100; // 1D
  *((volatile uint32_t *) 0x50d007f8) = 0x00002000; // Post processing register

  // Layer 27 quadrant 0
  *((volatile uint32_t *) 0x5010007c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x501001fc) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x501002fc) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x501003fc) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5010057c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x501005fc) = 0x000008a0; // Layer control
  *((volatile uint32_t *) 0x5010017c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x501007fc) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x5010077c) = 0x0000ffff; // Mask and processor enables

  // Layer 27 quadrant 1
  *((volatile uint32_t *) 0x5050007c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x505001fc) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x505002fc) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x5050037c) = 0x00008000; // SRAM write ptr
  *((volatile uint32_t *) 0x505003fc) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5050057c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x505005fc) = 0x000008a0; // Layer control
  *((volatile uint32_t *) 0x5050017c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x505007fc) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x5050077c) = 0x0000ffff; // Mask and processor enables

  // Layer 27 quadrant 2
  *((volatile uint32_t *) 0x5090007c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x509001fc) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x509002fc) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x5090037c) = 0x00010000; // SRAM write ptr
  *((volatile uint32_t *) 0x509003fc) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x5090057c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x509005fc) = 0x000008a0; // Layer control
  *((volatile uint32_t *) 0x5090017c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x509007fc) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x5090077c) = 0x0000ffff; // Mask and processor enables

  // Layer 27 quadrant 3
  *((volatile uint32_t *) 0x50d0007c) = 0x00000016; // Rows
  *((volatile uint32_t *) 0x50d001fc) = 0x00000001; // Pooling rows
  *((volatile uint32_t *) 0x50d002fc) = 0x00000001; // Stride
  *((volatile uint32_t *) 0x50d0037c) = 0x00018000; // SRAM write ptr
  *((volatile uint32_t *) 0x50d003fc) = 0x00002000; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d0057c) = 0x00001000; // SRAM read ptr
  *((volatile uint32_t *) 0x50d005fc) = 0x000008a0; // Layer control
  *((volatile uint32_t *) 0x50d0017c) = 0x00046003; // 1D
  *((volatile uint32_t *) 0x50d007fc) = 0x01000000; // Post processing register
  *((volatile uint32_t *) 0x50d0077c) = 0x0000ffff; // Mask and processor enables

  // Layer 28 quadrant 0
  *((volatile uint32_t *) 0x50100380) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50100400) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50100480) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50100600) = 0x0000e920; // Layer control
  *((volatile uint32_t *) 0x50100a80) = 0x0000080a; // Layer control 2
  *((volatile uint32_t *) 0x50100680) = 0x32a03348; // Mask offset and count
  *((volatile uint32_t *) 0x50100180) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50100800) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50100780) = 0xffffffff; // Mask and processor enables

  // Layer 28 quadrant 1
  *((volatile uint32_t *) 0x50500380) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50500400) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50500480) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50500600) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50500a80) = 0x0000080a; // Layer control 2
  *((volatile uint32_t *) 0x50500680) = 0x32a03348; // Mask offset and count
  *((volatile uint32_t *) 0x50500180) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50500800) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50500780) = 0xffffffff; // Mask and processor enables

  // Layer 28 quadrant 2
  *((volatile uint32_t *) 0x50900380) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50900400) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50900480) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50900600) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50900a80) = 0x0000080a; // Layer control 2
  *((volatile uint32_t *) 0x50900680) = 0x32a03348; // Mask offset and count
  *((volatile uint32_t *) 0x50900180) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50900800) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50900780) = 0xffffffff; // Mask and processor enables

  // Layer 28 quadrant 3
  *((volatile uint32_t *) 0x50d00380) = 0x00000800; // SRAM write ptr
  *((volatile uint32_t *) 0x50d00400) = 0x00000001; // Write ptr time slot offs
  *((volatile uint32_t *) 0x50d00480) = 0x00002000; // Write ptr mask offs
  *((volatile uint32_t *) 0x50d00600) = 0x00000920; // Layer control
  *((volatile uint32_t *) 0x50d00a80) = 0x0000080a; // Layer control 2
  *((volatile uint32_t *) 0x50d00680) = 0x32a03348; // Mask offset and count
  *((volatile uint32_t *) 0x50d00180) = 0x00000100; // 1D
  *((volatile uint32_t *) 0x50d00800) = 0x00022000; // Post processing register
  *((volatile uint32_t *) 0x50d00780) = 0xffffffff; // Mask and processor enables


  return CNN_OK;
}

int cnn_start(void)
{
  cnn_time = 0;

  *((volatile uint32_t *) 0x50100000) = 0x00100808; // Enable quadrant 0
  *((volatile uint32_t *) 0x50500000) = 0x00100809; // Enable quadrant 1
  *((volatile uint32_t *) 0x50900000) = 0x00100809; // Enable quadrant 2
  *((volatile uint32_t *) 0x50d00000) = 0x00100809; // Enable quadrant 3

#ifdef CNN_INFERENCE_TIMER
  MXC_TMR_SW_Start(CNN_INFERENCE_TIMER);
#endif

  CNN_START; // Allow capture of processing time
  *((volatile uint32_t *) 0x50100000) = 0x00100009; // Master enable quadrant 0

  return CNN_OK;
}

int cnn_unload(uint32_t *out_buf32)
{
  uint8_t *out_buf = (uint8_t *) out_buf32;
  uint32_t val;
  volatile uint32_t *addr;

  // Custom unload for this network, layer 28 (fc): 8-bit data, shape: (2, 1, 1)
  addr = (volatile uint32_t *) 0x50402000;
  val = *addr++;
  *out_buf++ = val & 0xff;
  *out_buf++ = (val >> 8) & 0xff;

  return CNN_OK;
}

int cnn_enable(uint32_t clock_source, uint32_t clock_divider)
{
  // Reset all domains, restore power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg1 = 0xf; // Mask memory
  MXC_GCFR->reg0 = 0xf; // Power
  MXC_GCFR->reg2 = 0x0; // Iso
  MXC_GCFR->reg3 = 0x0; // Reset

  MXC_GCR->pclkdiv = (MXC_GCR->pclkdiv & ~(MXC_F_GCR_PCLKDIV_CNNCLKDIV | MXC_F_GCR_PCLKDIV_CNNCLKSEL))
                     | clock_divider | clock_source;
  MXC_SYS_ClockEnable(MXC_SYS_PERIPH_CLOCK_CNN); // Enable CNN clock

  MXC_NVIC_SetVector(CNN_IRQn, CNN_ISR); // Set CNN complete vector

  return CNN_OK;
}

int cnn_boost_enable(mxc_gpio_regs_t *port, uint32_t pin)
{
  mxc_gpio_cfg_t gpio_out;
  gpio_out.port = port;
  gpio_out.mask = pin;
  gpio_out.pad = MXC_GPIO_PAD_NONE;
  gpio_out.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_out);
  MXC_GPIO_OutSet(gpio_out.port, gpio_out.mask);

  return CNN_OK;
}

int cnn_boost_disable(mxc_gpio_regs_t *port, uint32_t pin)
{
  mxc_gpio_cfg_t gpio_out;
  gpio_out.port = port;
  gpio_out.mask = pin;
  gpio_out.pad = MXC_GPIO_PAD_NONE;
  gpio_out.func = MXC_GPIO_FUNC_OUT;
  MXC_GPIO_Config(&gpio_out);
  MXC_GPIO_OutClr(gpio_out.port, gpio_out.mask);

  return CNN_OK;
}

int cnn_disable(void)
{
  // Disable CNN clock
  MXC_SYS_ClockDisable(MXC_SYS_PERIPH_CLOCK_CNN);

  // Disable power to CNN
  MXC_GCFR->reg3 = 0xf; // Reset
  MXC_GCFR->reg2 |= 0xf; // Iso
  MXC_GCFR->reg0 = 0x0; // Power
  MXC_GCFR->reg1 = 0x0; // Mask memory
  MXC_GCFR->reg3 = 0x0; // Reset

  return CNN_OK;
}

