/*******************************************************************************
* Copyright (C) 2019-2023 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// RTDemo_MAX_alpha
// This file was @generated by ai8xize.py --test-dir synthed_net --prefix RTDemo_MAX_alpha --checkpoint-file trained/tinyfallnet-qat8-q.pth.tar --config-file networks/tinyfallnet.yaml --sample-input tests/sample_kfall.npy --device MAX78000 --board-name FTHR_RevA --compact-data --mexpress --timer 0 --display-checkpoint --verbose --overwrite

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "cnn.h"
#include "sampledata.h"
#include "sampleoutput.h"

volatile uint32_t cnn_time; // Stopwatch

void fail(void)
{
  printf("\n*** FAIL ***\n\n");
  while (1);
}

// 6-channel 50x1 data input (300 bytes total / 50 bytes per channel):
// HWC 50x1, channels 0 to 3
static const uint32_t input_0[] = SAMPLE_INPUT_0;

// HWC 50x1, channels 4 to 5
static const uint32_t input_4[] = SAMPLE_INPUT_4;

void load_input(void)
{
  // This function loads the sample data input -- replace with actual data

  memcpy32((uint32_t *) 0x50400000, input_0, 50);
  memcpy32((uint32_t *) 0x50408000, input_4, 50);
}

// Expected output of layer 23 (fc) for RTDemo_MAX_alpha given the sample input (known-answer test)
// Delete this function for production code
static const uint32_t sample_output[] = SAMPLE_OUTPUT;
int check_output(void)
{
  int i;
  uint32_t mask, len;
  volatile uint32_t *addr;
  const uint32_t *ptr = sample_output;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    mask = *ptr++;
    len = *ptr++;
    for (i = 0; i < len; i++)
      if ((*addr++ & mask) != *ptr++) {
        printf("Data mismatch (%d/%d) at address 0x%08x: Expected 0x%08x, read 0x%08x.\n",
               i + 1, len, addr - 1, *(ptr - 1), *(addr - 1) & mask);
        return CNN_FAIL;
      }
  }

  return CNN_OK;
}

static int32_t ml_data32[(CNN_NUM_OUTPUTS + 3) / 4];

int main(void)
{
  MXC_ICC_Enable(MXC_ICC0); // Enable cache

  // Switch to 100 MHz clock
  MXC_SYS_Clock_Select(MXC_SYS_CLOCK_IPO);
  SystemCoreClockUpdate();

  printf("Waiting...\n");

  // DO NOT DELETE THIS LINE:
  MXC_Delay(SEC(2)); // Let debugger interrupt if needed

  // Enable peripheral, enable CNN interrupt, turn on CNN clock
  // CNN clock: APB (50 MHz) div 1
  cnn_enable(MXC_S_GCR_PCLKDIV_CNNCLKSEL_PCLK, MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1);

  printf("\n*** CNN Inference Test RTDemo_MAX_alpha ***\n");

  cnn_init(); // Bring state machine into consistent state
  cnn_load_weights(); // Load kernels
  cnn_load_bias();
  cnn_configure(); // Configure state machine
  load_input(); // Load data input
  cnn_start(); // Start CNN processing

  while (cnn_time == 0)
    MXC_LP_EnterSleepMode(); // Wait for CNN

  if (check_output() != CNN_OK) fail();
  cnn_unload((uint32_t *) ml_data32);

  printf("\n*** PASS ***\n\n");

#ifdef CNN_INFERENCE_TIMER
  printf("Approximate inference time: %u us\n\n", cnn_time);
#endif

  cnn_disable(); // Shut down CNN clock, disable peripheral


  return 0;
}

/*
  SUMMARY OF OPS
  Hardware: 746,496 ops (720,384 macc; 19,968 comp; 6,144 add; 0 mul; 0 bitwise)
    Layer 0 (conv1): 55,296 ops (55,296 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 1 (pool1): 3,072 ops (0 macc; 3,072 comp; 0 add; 0 mul; 0 bitwise)
    Layer 2 (convblk1_convr): 99,840 ops (98,304 macc; 1,536 comp; 0 add; 0 mul; 0 bitwise)
    Layer 3 (convblk1_conv1): 24,960 ops (24,576 macc; 384 comp; 0 add; 0 mul; 0 bitwise)
    Layer 4 (convblk1_conv2): 18,816 ops (18,432 macc; 384 comp; 0 add; 0 mul; 0 bitwise)
    Layer 5 (convblk1_conv3): 26,112 ops (24,576 macc; 1,536 comp; 0 add; 0 mul; 0 bitwise)
    Layer 6 (convblk1_resid): 1,536 ops (0 macc; 0 comp; 1,536 add; 0 mul; 0 bitwise)
    Layer 7 (convblk2_convr): 99,840 ops (98,304 macc; 1,536 comp; 0 add; 0 mul; 0 bitwise)
    Layer 8 (convblk2_conv1): 24,960 ops (24,576 macc; 384 comp; 0 add; 0 mul; 0 bitwise)
    Layer 9 (convblk2_conv2): 18,816 ops (18,432 macc; 384 comp; 0 add; 0 mul; 0 bitwise)
    Layer 10 (convblk2_conv3): 26,112 ops (24,576 macc; 1,536 comp; 0 add; 0 mul; 0 bitwise)
    Layer 11 (convblk2_resid): 1,536 ops (0 macc; 0 comp; 1,536 add; 0 mul; 0 bitwise)
    Layer 12 (convblk3_convr): 99,840 ops (98,304 macc; 1,536 comp; 0 add; 0 mul; 0 bitwise)
    Layer 13 (convblk3_conv1): 24,960 ops (24,576 macc; 384 comp; 0 add; 0 mul; 0 bitwise)
    Layer 14 (convblk3_conv2): 18,816 ops (18,432 macc; 384 comp; 0 add; 0 mul; 0 bitwise)
    Layer 15 (convblk3_conv3): 26,112 ops (24,576 macc; 1,536 comp; 0 add; 0 mul; 0 bitwise)
    Layer 16 (convblk3_resid): 1,536 ops (0 macc; 0 comp; 1,536 add; 0 mul; 0 bitwise)
    Layer 17 (convblk4_convr): 99,840 ops (98,304 macc; 1,536 comp; 0 add; 0 mul; 0 bitwise)
    Layer 18 (convblk4_conv1): 24,960 ops (24,576 macc; 384 comp; 0 add; 0 mul; 0 bitwise)
    Layer 19 (convblk4_conv2): 18,816 ops (18,432 macc; 384 comp; 0 add; 0 mul; 0 bitwise)
    Layer 20 (convblk4_conv3): 26,112 ops (24,576 macc; 1,536 comp; 0 add; 0 mul; 0 bitwise)
    Layer 21 (convblk4_resid): 1,536 ops (0 macc; 0 comp; 1,536 add; 0 mul; 0 bitwise)
    Layer 22 (pool2): 1,536 ops (0 macc; 1,536 comp; 0 add; 0 mul; 0 bitwise)
    Layer 23 (fc): 1,536 ops (1,536 macc; 0 comp; 0 add; 0 mul; 0 bitwise)

  RESOURCE USAGE
  Weight memory: 30,336 bytes out of 442,368 bytes total (6.9%)
  Bias memory:   688 bytes out of 2,048 bytes total (33.6%)
*/

